# argocd-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fastpick
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastpick
    spec:
      containers:
      - name: argocd-container
        image: kimrma370/team3:latest
        envFrom:
        - configMapRef:
            name: argocd-env-vars
